#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if __name__ == '__main__':
    from datetime import datetime
    print("Программа nwn запущена " + datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
